# Generated by Django 3.1.7 on 2021-04-01 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('mistreats_animals', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('picture_url', models.CharField(max_length=500)),
                ('date_found', models.DateTimeField()),
                ('place_found', models.CharField(max_length=500)),
                ('date_adoption', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orphanage_administrator.person')),
            ],
        ),
    ]
